example.property= I AM the changed DEV from git
spring.datasource.url = jdbc:postgresql://localhost:5432/ostock_dev
spring.datasource.username = postgres
spring.datasource.password = "{cipher} b1d06f111d08a900e4969f9a8c50f5c14a1f239e15c2afaf7de7ef2c7386e107"