example.property=I AM the changed DEV from git
spring.datasource.url=jdbc:postgresql://localhost:5432/ostock_dev
spring.datasource.username=postgres
spring.datasource.password={cipher} d6ef41da55029ae8d476e0309d99344f88691d727dc98726b416a64b296d5b82