server:
  port: 8072
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: ORGANISATION-SERVICE
          uri: lb://organisation-service
          predicates:
          - Path=/organisation/**
          filters:
          - RewritePath=/organisation/(?<path>.*), /$\{path}
        - id: LICENSING-SERVICE
          uri: lb://licensing-service
          predicates:
          - Path=/license/**
          filters:
          - RewritePath=/license/(?<path>.*), /$\{path}
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
        
eureka:
  instance:
    preferip-address: true
  client:
    #registerWithEureka: true
    #fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


    
    